[ElecChemParameter]
SupportChemistryType=0,1,2,3,4,5,6,8,9,10,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,32,33,34,35,36,37,38,39,40,49,50,52,56,63,64,65,66,67,70,112,113,115,116,117,118,119,120,121,91,92,93,114,75,76,82,90,111,98,99,100,124,125,126,127,128,129,130,141,142,143,148,149,150,151,153,155,156,157,158,161

;伏安法相关
;开路
ChemistryType0=101
ChemistryType91=101
ChemistryType114=101

;线性
ChemistryType1=104
ChemistryType111=104
;循环伏安法
ChemistryType2=102
ChemistryType3=102
;阶梯线性
ChemistryType4=105
ChemistryType128=105
;阶跃
ChemistryType5=103
ChemistryType6=103
ChemistryType127=103
ChemistryType130=103
;直流
ChemistryType8=101
ChemistryType9=101
ChemistryType10=101
ChemistryType90=101
ChemistryType112=101
ChemistryType113=101
ChemistryType115=101
ChemistryType116=101
ChemistryType117=101
ChemistryType118=101
ChemistryType119=101
ChemistryType120=101
ChemistryType121=101
ChemistryType141=101
ChemistryType142=101

;快速电压脉冲
ChemistryType13=109
ChemistryType129=109
ChemistryType155=109
;快速电流脉冲
ChemistryType14=109
;方波伏安法
ChemistryType15=106
;差分脉冲伏安法
ChemistryType16=107
;标准脉冲法
ChemistryType17=108
;计时电位法(多循环)
ChemistryType70=115
;循环伏安法多循环-新的
ChemistryType150=121
ChemistryType158=121
;阶梯循环伏安法多循环-新的
ChemistryType151=122

;腐蚀相关
;开路电位
ChemistryType19=101
;线性极化法
ChemistryType20=105
;Tafel
ChemistryType21=105
;动电位极化
ChemistryType22=105
ChemistryType143=105
;循环极化
ChemistryType23=103
;恒电位法
ChemistryType24=101
ChemistryType82=101
ChemistryType92=101
ChemistryType93=101
ChemistryType122=101
ChemistryType123=101
;电偶腐蚀
ChemistryType25=101
;恒电流法
ChemistryType26=101
;动电流法
ChemistryType27=105
;零电阻安培计
ChemistryType28=101
;电化学噪声
ChemistryType29=101

;交流阻抗(开路)
ChemistryType32=101
;交流阻抗(电压)
ChemistryType33=110
;交流阻抗(电流)
ChemistryType34=111
ChemistryType126=111
;Mott_Schottky
ChemistryType35=114
;Mott_Schottky_Current
ChemistryType125=114

;能源
;开路
ChemistryType36=101
;恒电位
ChemistryType37=101
;恒电流
ChemistryType38=101
ChemistryType75=101
ChemistryType76=101
;恒功率
ChemistryType39=112
;恒电阻
ChemistryType40=113

;电压充放电(这里先暂定120,后面可能会改)
ChemistryType148=123
;电流充放电
ChemistryType149=120

;预实验
;Deposition
ChemistryType49=101
;Equilibration
ChemistryType50=101
;溶液电阻补偿
ChemistryType52=110

;序列实验
;开路
ChemistryType56=101

;恒压源
ChemistryType63=101
;恒流源
ChemistryType64=101

;谐波
ChemistryType65=114
ChemistryType66=114
ChemistryType67=114

;中南大学新波形
ChemistryType98=117
ChemistryType99=116
ChemistryType100=118
ChemistryType124=116

;ND定频电压交流阻抗(触发)
ChemistryType153=116

ChemistryType154=125

;新的线性方法
ChemistryType156=126
;新的循环方法
ChemistryType157=127

;电解槽(开路)
ChemistryType161=101

;是否自动停止
IsAutoStop=1

;硬件版本
HardWareVersion=6

;是否调试
IsDebug=0

;阶跃采样和阶梯线性扫描的平均点数
AveCount1=50
AveCount2=100

;预采样时间(单位为ms)
PrepareSampleTime=1000

;参数设置码和采样码间隔时间(单位为ms)
DelayTime=0

;多少百分比的时候判断超量程
MaxRandPerent=0.99
MaxRandPerentForTiaoLiQi=0.99

;记录仪自动刻度的情况下算出来的最小最大刻度值乘以一个多大的倍数
RecorderYAutoScaleCoief=100

;记录仪X轴刻度系数
RecorderXScaleCoief=30

;XY记录仪自动刻度的情况下算出来的最小最大刻度值除以一个多大的倍数来决定左边和右边空出来的距离
;常用系数
XYRecorderXAutoScaleCoief=30
;大系数
XYRecorderXAutoScaleBigCoief=0.2

;是否启动定时判断逻辑
IsStartTimerLogic=0

;判断自动停止的最小间隔时间
MinInterval=0.5

;采样频率分水岭
SampleFreqCoteau=50

;采样频率大于SampleFreqCoteau的时候加几秒判断
;以及
;采样频率小于等于SampleFreqCoteau的时候在非阶梯实验的情况下加几秒判断
SecondWhenSampleFreqGreaterThanCoteau=2.2

;丢点频率(大于这个频率开始丢点)
LosePointSampleFreq=50

;非阶梯实验的丢点相关
LosePointInfoOfNonStaircaseExperiment=500,10,5,0,-1

;从哪个邮箱发送
FromMail=
FromPassword=

;邮件发送等待时间(以秒为单位)
MailSendDelay=3

;EIS是否使用滤波
IsFilter=0

;EIS是否往文件写原始数据
IsWriteEISSourceData=0

;是否在进行EIS测试
;这个配置改成1的话就会使用开始频率一直计算频谱值，并且把计算出来的5个值写到文件里面去
IsTestEIS=0

;EIS是否读取衰减系数
IsReadAttenuationCoief=1

;EIS是否使用衰减系数
IsUseAttenuationCoief=1

;小于等于多大数据量使用高质量画图
HighQualityMaxCount=2000

;交流阻抗模拟采样频率
IsEISAnalogSample=1

;多少数据量自动进行抽点
JumpMinCount=50000

;信号最大缓存
SignalBufferMaxCount=15000

;交流阻抗纯实验多大比例进行自动压缩
CompressBaseValue=3

;是否存在能源模块
IsSupportEnergy=1

;EIS不支持的量程档位(可以添加多个,用逗号隔开)
EISNotSupportRand=100

;EIS是否使用相同索引逻辑
IsEISSameIndex=1

;EIS定位值类型
EISSearchType=1

;NA级别滤波自动打到10Hz
IsAutoToTenHz=1

JHG=1

;是否用界面值进行计算
IsCalByUISetting=1

IsOpenCircuitZero=1

IsConsiderPotentialLineOverMax=0

;是否对恒定实验数据进行分析
IsAnalysisStaticExperiment=0

;恒定实验数据分析百分比
StaticExperimentAnalysisPercent=50

;是否启动电压实时刷新
IsRefreshVol=0

;丢点信息
;10000代表的是默认类型，其他代表的是对应的实验类型
;如果在下面配置了，那么在下面的LostPointInfo中也要配置,10000,0,19,32,36,33,34,52,20
LostPointExperimentType=20

;下面配置规则如下
;0.34是Hz,1是大于0.34Hz使用的丢点个数，0是小于0.34Hz使用的丢点个数,后面的0,-1是内部规则,请不要自己修改，

LostPointInfo10000=0.34,1,0,0,-1

;几个开路
LostPointInfo0=0.34,0,0,0,-1
LostPointInfo19=0.34,0,0,0,-1
LostPointInfo32=0.34,0,0,0,-1
LostPointInfo36=0.34,0,0,0,-1

;交流阻抗和IR补偿
LostPointInfo33=0.34,0,0,0,-1
LostPointInfo34=0.34,0,0,0,-1
LostPointInfo52=0.34,0,0,0,-1

;线性极化
LostPointInfo20=0.34,0,0,1,319;0.34,0,0,1,321;0.34,0,0,1,341;0.34,4,4,0,-1

;使用能源发码方式
EnergyCode=1,2,3,36,37,39,40,82,92,93,122,123
IsTestCodeSequence=0

;是否使用EIS平滑
IsUseEISSmooth=1

;MRIF定位
IsUseMRif=0

;线性扫描是否使用平滑
IsLineScanUseSmooth=0

;大于等于这个值认为是高速采样
HighSampleFreq=50000

IsUseRandCoief=1
IsCalByRandCoief=0

EISSmoothCount=3

IsCsUseZValue=0

IsExistMainSlaveMachine=0

IsAuthApplication=1
IsForverWork=1
IsCloseScreen=1
IsConsiderCover=1

RightValueCoief=0.02

;是否支持恒流的充放电
IsSupportConstantCurrentChargeDisCharge=0

IsAutoModifyIP=1
TargetIP=

TableInfos=5000,40,1|4000,100,1|3000,200,1|2000,1000,0

IsDoOpenCircuitForStaticCurrent=1

Is8300_7002=0

IsSupportZCurrent=0

ZCurrentMaxFreq=1000000

IsRandFake=0

OverMaxCoief=0.05

IsSupport7003Special=0

IsUICHI=0
IsCHI=0
HardWareLineExperimentMaxSweptRate=20

IsSupportJumpSignal=0

IsForceFindAlgorithmInfo=0

MaxBufferExperimentInfoCount=5

MaxBufferSegmentInfoCount=2

IsInternalDebug=0

;是否使用外部tcp控制
IsUseTcpControl=0
;外部tcp控制端口
TcpControlPort=7000

;是否支持自动导出数据
IsSupportAutoExportData=1
;是否自动导出数据
IsAutoExportData=0
;自动导出类型
AutoSaveType=1
;自动导出目录
AutoExportFolder=


IsModifyHardWareCfg=1

IsSupportIRFastGalvanic=0

IsSupportNewChargeDisCharge=0
IsSupportNewChargeDisCharge_Current=0

;是否显示新的阶梯方法
IsSupportMultipleCycles=0

;是否显示新的线性和循环方法
;如果是空白,那么就是默认状态
;如果是0,那么显示旧方法
;如果是1,那么显示新方法
IsSupport_Line_Cycles_StepHeight=

IsSupportLaPu=0

IsConsiderEISLostPoint=1

IsSignalSourceAutoPass=0

CurrentAutoCoief=1

IsShowSignalSource=0

MultChannelInstrumentType=236,237,310

SerialBufferCount=204800
ExperimentMaxDataCount=2000000

IsWPFWindow=1

;用模拟电解池的时候用这个电阻值100, 100, 100, 100, 100, 100, 100, 100, 100, 100
EISCalibrationCommon=120, 120, 120, 120, 120, 120, 120, 120, 120, 120
EISCalibrationCommonShow=120Ω, 120Ω, 120Ω, 120Ω, 120Ω, 120Ω, 120Ω, 120Ω, 120Ω, 120Ω
EISCalibration7007=120,120,120,120,120,1000,1000,10000,10000,100000,100000,1000000,1000000,10000000,10000000,112000000,1000000000,10000000000,120,120,120,120,120,1000,1000,10000,10000,100000,100000,1000000,1000000,10000000,10000000,112000000,1000000000,10000000000
EISCalibration7007Show=120Ω,120Ω,120Ω,120Ω,120Ω,1kΩ,1kΩ,10 kΩ,10 kΩ,100 kΩ,100 kΩ,1MΩ,1MΩ,10MΩ,10MΩ,56MΩ串56MΩ,1GΩ,10GΩ,120Ω,120Ω,120Ω,120Ω,120Ω,1kΩ,1kΩ,10 kΩ,10 kΩ,100 kΩ,100 kΩ,1MΩ,1MΩ,10MΩ,10MΩ,56MΩ串56MΩ,1GΩ,10GΩ

IsGongFangSupportLoop=0

SquareExperimentMaxFreq=1000

HumorousWaveMaxFreq=1000

PlusMaxWidth=100

StepTime=3E-4

MaxSampleFreq=500000

IsShowCustomExperiment=1

IsStaticCurrentShowGalvanoStaticEIS=0

IsSendCodeShowMessageBox=0

;SternB计算系数 B=ba*bc/2.303（ba+bc）
SternBCoef=2.303

;腐蚀速率计算系数 V（mm/a）=1000*3.27icorrA/nDs
CorrosionSpeedCoef=3270

;腐蚀速率另一种表达方式计算系数 V（mil/year，mpy）=V（mm/a）/0.0254
CorrosionSpeedPerYearCoef=0.0254

;交换电流密度计算系数 电流密度=0.025687/（SnRp）
AmpereDensityCoef=0.025687

;原界面显示时会将拟合出的斜率除以系数2.303(TaferCalibrationResult.GetDisplayResult)
SlopeCoef=2.303

;腐蚀电位开始的电位范围, 默认为60, 即阴极比腐蚀电位低60mV, 阳极比腐蚀电位高60mV
TafelFitRange=60

;线性极化电位范围, 默认20, 即腐蚀电位-20mV 至 腐蚀电位+20mV
PolarizationRange=20

;视图上面是否显示工程名称
IsChartShowProjectName=1

;Zim-Zre视图画最接近0的线, 小于该值才画线, 必须用科学计数法
ZeroLineLimit=1E-5

;最大叠加工程个数
MaxWrapProjectCount=8

;是否显示电压功放
IsShowVolGongFang=0

;吉林大学 是否显示限制电量、电流
IsEnableQLimit=1

;是否开启电源保护措施
IsEnablePowerProtection=1
;支持电源保护的仪器类型(7000,7006)
PowerProtectionInstrumentType=233,236
;触发提示值, 逗号隔开, 跟仪器类型一一对应
PowerProtectionTipsValue=800,500
;触发停止值, 逗号隔开, 跟仪器类型一一对应
PowerProtectionStopValue=850,600

IsShowMottSourceData=0
IsUseNewMottFreq=0
IsWriteLog=1
RealTimeLostPointPercent=50

ForceShowAllVoltageRand=341
ForceShowAllVoltageRandOfCommon=398,407

;渲染模式, 1 默认 0 禁用硬件加速
IsRenderModeDefault = 1

;用于连接西门子PLC 200Smart的TCP服务端
IsUsePLCTCPServer = 0
PLCTCPServerIP = 127.0.0.1
PLCTCPServerPort = 33333
PLCTCPServerPath = PLCServer\SiemensTCPServer.exe

IsStartServer=0

;是否支持追加采集
IsSupportKeepSample=0

IsSupportBackgroudNoise=0

IsForceNotUseAutoRand=0

;是否强制打开腐蚀计算窗口 如果实验不支持则腐蚀计算窗口禁用，为兼容老版本数据，可以开启强制打开
IsForceUseCorrosionCal=0

IsMottSizeAutoCal=0
MottSizeIncrease=1

IsConsiderReCalOpenCircuit=1

DigitalCount=3

AdvancedSampleCount=237,8,2

IRStartFreq=10000
IREndFreq=100

CycleIntervalTime=1

IsSupportStillElectricityCoief=0

IsSupportCopyData=0

IsStartSampleNotShowExperimentParam=0

IsDefaultHorizonWave=0

HorizonWaveInterval=0.5

IsCoiefConsiderFreq=0

IsForceLayOut=1

IsSupportTHD=1

;除了代码固定的计算电量Q的方法外，其他需要计算的方法类型
CalQExperimentType=

;计算电量是否考虑电流的绝对值
IsCalQByAbsolute=0

;是否实时刷新电量值
IsRealTimeShowQ=0

;是否支持电极类型的选择
IsSupportElectrodeType=0

;方波自动滤波系数
SquareAutoFilterCoief=100

ResistanceCoief=0.1

HelpPostion=0