[SystemParameter]
InstrumentType = 400
InterfaceType = 7
; 0(EPP);1(1394);2(USB);3(Rs232);4(Demo);5(EISA);6(NET);7(千兆网);8(4G);9(PCI);10(EtherCAT) = 
;多仪器分组 = 
MultiHardWareManage = 0
;分组数 = 
MultiHardWareManageCount = 0
;调试 = 
Debug = 0
;是否需要同步时钟 = 
UseClock = 1
;同步模式: 0-常规同步5611同步;1-GPS同步;2-1588同步;3-DH5611-1同步;4-级联同步 = 
ClockType = 0
;是否分组功能 = 
UseTeam = 0
;是否高低速采样 = 
SupportHLSample = 0
;是否支持主控与多客户端模式 = 
MultiClient = 0
;主控端 = 
MainServer = 1
;客户端数 = 
ServerCount = 1
;CS连接方式 0-域名;1-ip地址 = 
CSUseIP = 1
;主控端IP = 
ServerIP = 127.0.0.1
;主控端端口 = 
ServerPort = 4280
;域名 = 
DomainName = 127.0.0.1
;是否自定义版本 = 
CustomVersion = 0
;版本 = 
Version = 
;是否支持NTP同步 = 
NTPSync = 0
;支持moog功能 = 
SupportMoog = 0
;成飞加载系统 = 
MTS = 0
;是否支持用户管理 = 
IsSupportUserMgr = 0
;当前是否在使用5907M监测软件 = 
IsMonitor5709 = 0
IsAdministrator = 1
IsActivex = 0
IsEIS = 1
IsWriteDebugInfo = 0
IsRound = 0
IsNewFreqSection = 0
IsUseSignalFreq = 0
IsCopyToClipboard = 0
BufferDataType = Time,E,I,Zre,Zim,Z,Freq,Phase
BufferMaxCount = 500000
IsInitSplit = 0
AdvancedSampleCount = 1
Coief = 5
IsCheckOverTime = 0
