"""M-4: bundle -> device_pair.generated.yaml, Phase 1A compatible (contract C-3)."""

import json
from pathlib import Path

from unilabos.registry.pair_registry import PairRegistry
from unilabos.sim.pairs.bundle import parse_bundle
from unilabos.sim.pairs.generate import bundle_to_pairs_yaml, write_generated_pairs

FIXTURES = Path(__file__).parent / "fixtures"


def _bundle():
    return parse_bundle(json.loads((FIXTURES / "bundle_ok.json").read_text(encoding="utf-8")))


def test_generated_yaml_loads_in_pair_registry(tmp_path):
    out = write_generated_pairs(_bundle(), tmp_path / "device_pair.generated.yaml")
    reg = PairRegistry(out)

    e = reg.lookup("dalong_heaterstirrer")
    assert e.virtual == "community.dalong.virtual_heaterstirrer"
    assert e.missing_sim_policy == "stub"
    assert e.engine == "gazebo"
    assert e.twin_observed == ["temperature", "rpm"]  # from twin_capability.observed
    assert e.twin_throttle_hz == 20

    nmr = reg.lookup("qone_nmr")
    assert nmr.virtual is None
    assert nmr.missing_sim_policy == "fail"
    assert nmr.twin_observed == []  # twin_capability disabled


def test_generated_matches_expected_fixture(tmp_path):
    """Generated YAML must equal the frozen C-3 expectation at field level."""
    gen = write_generated_pairs(_bundle(), tmp_path / "gen.yaml")
    gen_reg = PairRegistry(gen)
    exp_reg = PairRegistry(FIXTURES / "expected_device_pair.yaml")

    for real in ("dalong_heaterstirrer", "qone_nmr"):
        g, x = gen_reg.lookup(real), exp_reg.lookup(real)
        assert (g.virtual, g.missing_sim_policy, g.engine, g.twin_observed, g.twin_throttle_hz) == (
            x.virtual, x.missing_sim_policy, x.engine, x.twin_observed, x.twin_throttle_hz
        )


def test_generated_yaml_has_header():
    assert bundle_to_pairs_yaml(_bundle()).startswith("# generated by Uni-Lab-OS Edge")
