"""Compile a PairBundle into a Phase 1A compatible device_pair.yaml (contract C-3 / M-4).

Output must be parseable by ``unilabos.registry.pair_registry.PairRegistry`` without
changes (keys: real / virtual / missing_sim_policy / twin_observed / twin_throttle_hz).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from unilabos.sim.pairs.bundle import PairBundle

_HEADER = (
    "# generated by Uni-Lab-OS Edge from Device Square simulation pair bundle\n"
    "# do not edit manually\n"
)


def bundle_to_pairs_dict(bundle: PairBundle) -> dict[str, Any]:
    pairs: list[dict[str, Any]] = []
    for e in bundle.pairs:
        item: dict[str, Any] = {
            "real": e.real,
            "virtual": e.virtual,
            "missing_sim_policy": e.missing_sim_policy,
        }
        if e.twin_observed:
            item["twin_observed"] = list(e.twin_observed)
        if e.twin_throttle_hz:
            item["twin_throttle_hz"] = e.twin_throttle_hz
        pairs.append(item)
    return {"pairs": pairs}


def bundle_to_pairs_yaml(bundle: PairBundle) -> str:
    return _HEADER + yaml.safe_dump(bundle_to_pairs_dict(bundle), sort_keys=False, allow_unicode=True)


def write_generated_pairs(bundle: PairBundle, path: str | Path) -> Path:
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(bundle_to_pairs_yaml(bundle), encoding="utf-8")
    return out
